
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '856C3F17A9A462ABF2037D571C41B2FD'
    
_lr_action_items = {'CLOSE':([0,16,],[1,1,]),'$end':([2,3,4,5,6,7,8,9,11,12,13,14,15,17,18,19,20,21,22,23,],[0,-2,-3,-6,-1,-4,-5,-7,-9,-12,-14,-13,-15,-16,-17,-19,-10,-18,-8,-11,]),'CONCAT':([2,3,4,5,6,7,8,9,11,12,13,14,15,17,18,19,20,21,22,23,],[16,-2,-3,-6,-1,-4,-5,-7,-9,-12,-14,-13,-15,-16,-17,-19,-10,-18,16,-11,]),'WEB':([10,],[17,]),'TEXTFILE':([1,10,],[14,18,]),'IMAGEFILE':([1,10,],[15,19,]),'PROGRAMS':([1,10,20,],[12,20,23,]),'MEDIAFILE':([1,10,],[13,21,]),'RUN':([0,16,],[10,10,]),'SEARCH':([0,16,],[11,11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,16,],[2,22,]),'closeprogram':([0,16,],[7,7,]),'search':([0,16,],[3,3,]),'openbrowser':([0,16,],[4,4,]),'openmusicfile':([0,16,],[8,8,]),'openimagefile':([0,16,],[9,9,]),'opentextfile':([0,16,],[5,5,]),'openprogram':([0,16,],[6,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> openprogram','expression',1,'p_expression','run.py',52),
  ('expression -> search','expression',1,'p_expression','run.py',53),
  ('expression -> openbrowser','expression',1,'p_expression','run.py',54),
  ('expression -> closeprogram','expression',1,'p_expression','run.py',55),
  ('expression -> openmusicfile','expression',1,'p_expression','run.py',56),
  ('expression -> opentextfile','expression',1,'p_expression','run.py',57),
  ('expression -> openimagefile','expression',1,'p_expression','run.py',58),
  ('expression -> expression CONCAT expression','expression',3,'p_expression','run.py',59),
  ('search -> SEARCH','search',1,'p_search','run.py',63),
  ('openprogram -> RUN PROGRAMS','openprogram',2,'p_openprogram','run.py',71),
  ('openprogram -> RUN PROGRAMS PROGRAMS','openprogram',3,'p_openprogram','run.py',72),
  ('closeprogram -> CLOSE PROGRAMS','closeprogram',2,'p_closeprogram','run.py',83),
  ('closeprogram -> CLOSE TEXTFILE','closeprogram',2,'p_closeprogram','run.py',84),
  ('closeprogram -> CLOSE MEDIAFILE','closeprogram',2,'p_closeprogram','run.py',85),
  ('closeprogram -> CLOSE IMAGEFILE','closeprogram',2,'p_closeprogram','run.py',86),
  ('openbrowser -> RUN WEB','openbrowser',2,'p_openbrowser','run.py',95),
  ('opentextfile -> RUN TEXTFILE','opentextfile',2,'p_opentextfile','run.py',101),
  ('openmusicfile -> RUN MEDIAFILE','openmusicfile',2,'p_openmusicfile','run.py',107),
  ('openimagefile -> RUN IMAGEFILE','openimagefile',2,'p_openimagefile','run.py',113),
]
